language: python

python:
  - "2.7"
  - "3.4"

before_script:
  - pip install coveralls
  - ./ci/start-ci.sh $ORIENTDB_VERSION

script: nosetests -vv --with-coverage --cover-xml --cover-erase --cover-package=pyorient

after_success:
  - coveralls

env:
  - ORIENTDB_VERSION=2.0-rc2
  - ORIENTDB_VERSION=1.7.10
  - ORIENTDB_VERSION=1.7.7
  - ORIENTDB_VERSION=1.7.4

matrix:
  allow_failures:
#    - env: ORIENTDB_VERSION=1.7.7
