language: python

python:
  - "2.7"
  - "3.4"

before_script:
  - pip install coveralls
  - ./ci/start-ci.sh $ORIENTDB_VERSION

script: nosetests -vv --with-coverage --cover-xml --cover-erase --cover-package=pyorient

after_success:
  - coveralls

env:
  - ORIENTDB_VERSION=2.1-rc4
  - ORIENTDB_VERSION=2.0.10
  - ORIENTDB_VERSION=2.0.8
  - ORIENTDB_VERSION=2.0.7
  - ORIENTDB_VERSION=2.0.6
  - ORIENTDB_VERSION=2.0.5
  - ORIENTDB_VERSION=2.0.4
  - ORIENTDB_VERSION=2.0.3
  - ORIENTDB_VERSION=2.0.2
  - ORIENTDB_VERSION=2.0.1
  - ORIENTDB_VERSION=1.7.10
  - ORIENTDB_VERSION=1.7.8
  - ORIENTDB_VERSION=1.7.7
  - ORIENTDB_VERSION=1.7.4

matrix:
  allow_failures:
    - ORIENTDB_VERSION=1.7.10
    - ORIENTDB_VERSION=1.7.8
    - ORIENTDB_VERSION=1.7.7
    - ORIENTDB_VERSION=1.7.4
