language: python

python:
  - "2.7"
  - "3.4"

before_script:
  - ./ci/start-ci.sh $ORIENTDB_VERSION

script: nosetests -vv

env:
  - ORIENTDB_VERSION=2.0-rc2
  - ORIENTDB_VERSION=1.7.10
  - ORIENTDB_VERSION=1.7.7
  - ORIENTDB_VERSION=1.7.4

matrix:
  allow_failures:
#    - env: ORIENTDB_VERSION=1.7.7
